#This file contains the default stats and general stat categories

STATS = {'intelligence' : 1,
              'wits' : 1,
              'resolve' : 1,
              'strength': 1,
              'dexterity' : 1,
              'stamina' : 1,
              'presence' : 1,
              'manipulation' : 1,
              'composure' : 1,
              'academics' : 0,
           'computer' : 0,
           'crafts' : 0,
           'investigation' : 0,
           'medicine' : 0,
           'occult' : 0,
           'politics' : 0,
           'science' : 0,
           'athletics' : 0,
           'brawl' : 0,
           'drive' : 0,
           'firearms' : 0,
           'larceny' : 0,
           'stealth' : 0,
           'survival' : 0,
           'weaponry': 0,
           'animal ken' : 0,
           'empathy' : 0,
           'expression' : 0,
           'intimidation' : 0,
           'persuasion' : 0,
           'socialize' : 0,
           'streetwise' : 0,
           'subterfuge' : 0,
         'skill specialties' : {},
         'merits': {},
         'gnosis': 1,
         'wisdom': 7,
         'size' : 5,
         'conditions' : {},
         'aspirations' : {},
         'rotes' : {},
         'tilts' : {},
         'numbus' : '',
         'nimbus tilt' : {},
         'praxes' : {},
         'mana' : 0,
         'mana used' : 0,
         'mana extra' : 0,
         'willpower' : 0,
         'willpower filled'  : 0,
         'health' : [0,#max (derived)
                     0,#bashing
                     0,#lethal
                     0 #agg
                     ],
         'xp' : 0,
         'beats' : 0,
         'arcane xp' : 0,
         'arcane beats' : 0,
         'death' : 0,
          'fate' : 0,
          'forces' : 0,
          'life' : 0,
          'matter' : 0,
          'mind' : 0,
          'prime' : 0,
          'spirit' : 0,
          'space' : 0,
          'time' : 0,
         'user id': '',
         'webhook': '',
         'shadow name': '',
         'concept' : '',
         'order' : '',
         'legacy' : '',
         'legacy attainments' : [],
         'virtue' : '',
         'vice' : '',
         'path': '',
         'rote skill' : set([]),
         'armor' : 0,
         'initiative mod' : 0,
         'size mod' : 0,
         'speed mod' : 0,
         'defense mod': 0}

HEADERS = [['shadow name', 'user id', 'webhook'],
           ['concept','virtue','vice'],
           ['path', 'order', 'legacy']]
         
         

ARCANA = ['death',
          'fate',
          'forces',
          'life',
          'matter',
          'mind',
          'prime',
          'spirit',
          'space',
          'time']


ATTRIBUTE_TYPE = {'mental' : ['intelligence', 'wits', 'resolve'],
                  'physical' : ['strength', 'dexterity', 'stamina'],
                  'social' : ['presence', 'manipulation', 'composure']
                  }

SKILL_TYPE = {'mental': ['academics',
                     'computer',
                     'crafts',
                     'investigation',
                     'medicine',
                     'occult',
                     'politics',
                     'science'],
          'physical' : ['athletics',
                        'brawl',
                        'drive',
                        'firearms',
                        'larceny',
                        'stealth',
                        'survival',
                        'weaponry'],
          'social' : ['animal ken',
                      'empathy',
                      'expression',
                      'intimidation',
                      'persuasion',
                      'socialize',
                      'streetwise',
                      'subterfuge']}

SKILLS = list(SKILL_TYPE.values())
SKILLS = sum(SKILLS, [])
